### PR TITLE
CMake fixes

### PR DESCRIPTION
**Pull request by johnmcfarlane**
A few minor fixes to CMake builds:

- suppress warnings in Boost
- remove ineffective CMake flag
- select C++20 in CMake Actions job

### CODE REVIEW

**Comment by ckormanyos** [comment]
OK. So this PR is now cycling on CI.

In the `constexpr` PR, however, I found a [timeout](https://github.com/ckormanyos/wide-integer/runs/2491899439?check_suite_focus=true#step:4:973). Is that anything you can control, John.

**Comment by ckormanyos** [comment]
@johnmcfarlane the `cmake` build timed out twice on CI, so i added `-O2` to your CXX flags, not knowing if that was exactly what you want or not. I had to do something like either that or cut out the `cmake` build from CI entirely. Or, which is often the cas for me, i missed somehing and had a misunderstanding.

Anyway, running in CI now OK with `-O2`

**Comment by johnmcfarlane** [comment]
Yes release mode will fix this. I've been off the computer all day. Will get to this in an hour or so

**Comment by ckormanyos** [comment]
> release mode will fix this

OK. Thank you.

**Comment by ckormanyos** [comment]
If you do decide to plow on with that, i would actually like to see an MSVC build on CMake, if that fits within your design it might be nice to have one of those for reference as we trudge on forward.

**Comment by johnmcfarlane** [comment]
https://github.com/johnmcfarlane/wide-integer/pull/2

**Pull request merged**
