### PR TITLE
Use default copy and move constructors, assignment operators

### PR DESCRIPTION
**Pull request by vaivaswatha**
This allows `uintwide_t` to be trivially copyable.

Static asserting trivially copyable and standard layout ensures
that objects of `uintwide_t` can be exchanged with extern C
functions.

### CODE REVIEW

**Comment by ckormanyos** [comment]
Thanks for looking into this @vaivaswatha.

Somehow, I was seeking this kind of clarity of expression, but it had eluded me. I just fired up CI via approval of your run. Let's see how CI runs...

**Comment by ckormanyos** [comment]
This change exercises additional constructors in some of the Boost-related tests.

At the same time, CI runs with -Werror, which is why all those errors are occuring in CI.

Hmmm... What's the best way to deal with this. The Boost-related files disable relevant warnings with `#pragma`.

@vaivaswatha: Could you please:
- Either add more disable warnings to GCC/clang and retry.
- Or temporarily eliminate `-Werror` in the YAML file?

Or do you need hwlp with this? I can also merge your PR into a branch and take a further look. But it would actually be best if you could get your PR to, let's say, _go_ _green_.

What do you say?

**Comment by ckormanyos** [comment]
Wait a second...

There has been a lot of recent activity preparing for Boost 1.77 and I am running wide-integer's CI with Boost's develop branch. I am checking if these warnings come from recent changes in Boost. In that case, to be seen, then I'll change main branch.

**Comment by ckormanyos** [comment]
Actually, the warning/errors in CI are due to new Boost-1.77-related changes on Boost-develop branch.

I am fixing wide-integer in main branch now...

**Comment by ckormanyos** [comment]
Hi @vaivaswatha the CI problems were related to Boost preparations for 1.77, running CI on develop branch of Boost and having `-Werror` enabled in CI.

These problems have now been fixed in wide-integer master.

You should be fine if you merge master into your branch and we crank up CI again...

**Comment by vaivaswatha** [comment]
> Hi @vaivaswatha the CI problems were related to Boost preparations for 1.77, running CI on develop branch of Boost and having `-Werror` enabled in CI.
> 
> These problems have now been fixed in wide-integer master.
> 
> You should be fine if you merge master into your branch and we crank up CI again...

Thank you @ckormanyos . I've updated my branch now.

**Comment by ckormanyos** [comment]
> I've updated my branch now

Hi @vaivaswatha thanks. I have just started CI. For some reason on a collaborator's first PR, CI needs to be manually approved.

**Comment by vaivaswatha** [comment]
>Thanks for your contribution @vaivaswatha and if anything else arises, please feel free to address such potential points may they arise.

Definitely, thank you @ckormanyos

**Pull request merged**
