### PR TITLE
Refine tidy and outer namespace fixes

### PR DESCRIPTION
**Pull request by ckormanyos**
This PR further refines the `clang-tidy` and outer-namespace fixes.

It properly handles `util::dynamic_array` for systems such as embedded systems using it.

It also includes the CMake tidy fix of #167 and also `NOLINT`s the `clang-tidy`messages found in the CI jobs thereof.

Cc: @johnmcfarlane

### CODE REVIEW

**Comment by johnmcfarlane** [comment]
> It also includes the CMake tidy fix of #167 and also NOLINTs the clang-tidymessages found in the CI jobs thereof.

Finally the dust is starting to settle. Sorry again for not removing that `NOLINTBEGIN` comment. Absolutely the worst change I could have made this weekend! 😆 

I've a few suggestions for keeping on top of a busy repo...

Even though it may cause multiple runs of the workflow, you may find that isolating changes into separate, minimal pull requests make things easier to follow. These PRs then focus on one single change, rather than a mixture of changes that are hard to pick apart in review or hindsight.

Also, rebasing branches - rather than merging them - tends to keep the commit graph more narrow and easier to track. I'd recommend playing with the `git rebase` command there (although never for the main branch!).

Finally, you don't have to take my changes and re-commit them. In fact, I'd generally prefer if my contributions remained attributable to me. Where possible, can you either merge my PRs or request changes to them? At the very least, consider the `git cherry-pick` command if you feel that my commits should be part of a longer branch (although I find smaller PRs are better for reasons I mentioned above).

**Comment by ckormanyos** [comment]
> I've a few suggestions 

All good advice. Thanks John.

> rebasing branches - rather than merging them

Yeah. This plays a bit on my lack of detailed Git/integration knowledge. I'm still learning some finer details...

> Finally, you don't have to take my changes and re-commit them. In fact, I'd generally prefer if my contributions remained attributable to me. Where possible, can you either merge my PRs or request changes to them? At the very least, consider the `git cherry-pick` command...

I guess that would have been a good case for a cherry pick. There were new CI jobs and i needed 3 lines from CMake file.

**Comment by johnmcfarlane** [comment]
Two ways I use to extract individual changes from a file: tools like git gui let you select lines and stage then; change to a new branch, reset to the main branch, then manually undo the changes you want to defer.

**Comment by ckormanyos** [comment]
> Two ways I use to extract individual changes from a file: tools like git gui let you select lines and stage then; change to a new branch, reset to the main branch, then manually undo the changes you want to defer.

Good stuff. Thx.

Alright @johnmcfarlane after that unseasonably active time in wide-integer, things are settling in nicely...

So now the preprocessor logic of the outer namespace is about as simple as I can get it without fundamentally changing it (which I don't want to do, as I am happy with it).

Also `clang-tidy` is running happily on GNUmake and CMake builds in CI.

I was hoping you would no longer need (in cnl) to disable [here](https://github.com/johnmcfarlane/cnl/blob/fab65d10641abe0da607675111d1af23df8a9fe1/include/cnl/_impl/ckormanyos/uintwide_t.h#L1). Should I do even more tidying up or activate some additional checks? Did I miss something, as I was hoping you could have active tidy checks running also on `uintwide_t.h`...?

**Comment by johnmcfarlane** [comment]
As I mentioned, I don't think you're checking for the new rules in the the CMake jobs because .clang-tidy hasn't had its exclusions removed.

Also, the ruleset in CNL's .clang-tidy file enforces other things that wide-integer hasn't (and may never) addressed. In particular, I enforce a naming convention. Just to double-check, I removed the file-wide `NOLINTBEGIN` to see what would break. [Here is the result](https://github.com/johnmcfarlane/cnl/runs/4755580131?check_suite_focus=true).

**Comment by ckormanyos** [comment]
> As I mentioned, I don't think you're checking for the new rules in the the CMake jobs because .clang-tidy hasn't had its exclusions removed.

Indeed. I can see7resolve that better now. I'll make `.clang-tidy` consistent (at least) with my command line(s) in GNUmake.

> Also, the ruleset in CNL's .clang-tidy file enforces other things that wide-integer hasn't (and may never) addressed. In particular, I enforce a naming convention. Just to double-check, I removed the file-wide NOLINTBEGIN to see what would break. [Here is the result](https://github.com/johnmcfarlane/cnl/runs/4755580131?check_suite_focus=true).

Oh yeah, cast-away. Not bad... --- 400 `static_cast<>()`s and a few real things. This kind of inspires me to go for a second round of ... tidying --- see also _new_ issue #170

**Comment by johnmcfarlane** [comment]
Again, I'd urge you to bite off small chunks of work in self-contained PRs. They're so much easier to review when they're just, e.g. a hundred static casts, or fifty reordered includes. And if you can make sure that the cmake job fails when you remove the - line, that gives certainty that the tool is actually working...

**Pull request merged**
