### PR TITLE
Constant expressions C++20

### PR DESCRIPTION
**Pull request by johnmcfarlane**
I had removed all of the functions from the `<algorithms>` header because they're not constant expressions in C++17 and then hit the problem that `std::array::array` isn't a constant expression in C++17!

I thought about it some more and realised that with a few changes, we could support C++20 constant expressions without breaking C++11 compatibility: by only conditionally expecting it in the tests. So...

* Added an ugly macro, `UINTWIDE_T_TEST_CONSTEXPR` which is defined as `constexpr` but *only when C++20 code is being compiled*.
* Use `UINTWIDE_T_TEST_CONSTEXPR` in the tests in _examples/_ so that when C++20 is being testing (e.g. in Actions) it will fail if anything is missing from _math/wide_integer/uintwide_t.h_ that would be required for C++20 constexpr conformance.

@ckormanyos how does this sound as a way to support `constexpr` without deserting any existing C++11/14/17 users?

### CODE REVIEW

**Comment by johnmcfarlane** [comment]
Note that I've added a bogus commit to the branch: "test test". It deliberately *breaks* C++20 constexpr conformance. This branch *should not be merged* until this commit breaks the C++20 build in Actions. That way we know the conformance testing is working!

**Comment by johnmcfarlane** [comment]
I've enabled the pipeline just in the branch and have identified plenty to keep me busy before this PR is ready for review! I'll ping you when it's green.

**Comment by ckormanyos** [comment]
Hi John,

I am following with great interest. In the meantime, however, @johnmcfarlane I did some unrelated cleanup and implemented an optional potential optimization. Not surprisingly, there are now merge conflicts in the main header file.

I will attempt to resolve these in a branch soon and report when finished.

**Comment by johnmcfarlane** [comment]
I resolved some conflicts earlier today after you merged to master. Happy to do that again. I've got most jobs passing now but need to do a formatting pass later today when I get time so don't worry about it.

**Comment by ckormanyos** [comment]
Also @johnmcfarlane in the code I would still like to stick with support for C++11, 14, 17. In all the back-and-forth I hope that was clear. C++20 I would somehow like to activate as a specific build option (unless the `constexpr` changes are also compatible with C++11, in which case, I' happy).

@johnmcfarlane So..., what exactly is this branch going for? C++20 alone or back-support of 11 thorugh 20 nonetheless with `consetexpr`_correctness_?

**Comment by ckormanyos** [comment]
Wait, now I see more clearly what you are doing...

You use the macro `WIDE_INTEGER_CONSTEXPR` in order to try for C++11 through 20 with the goal of having it work the way you want it to work (or mostly) for 20 while retaining 11 support.

Is that about the right interpretation?

I can make a dedicated branch in the main repo for this purpos if that helps...?

**Comment by ckormanyos** [comment]
@johnmcfarlane one more request, ...

I would like to differentiate between C++11 `constexpr` and C++20 `constexpr`. We do something like this in Boost.

For the C++11 version, I would like to use the actual keyword `constexpr`, whereas the preprocessor definition `WIDE_INTEGER_CONSTEXPR` expands to either nothing (for legacy versions of the standard) and `constexpr` for C++20.

In this way the minimal C++11 `constexpr` support (which believe it or not actually did some good, i.e., for `numeric_limits`, etc.) will be maintained.

**Comment by ckormanyos** [comment]
> differentiate between C++11 `constexpr` and C++20 `constexpr`

This commit 1eda802ad9dca9de3638ef03d85a2f4a7ff1d097
differentiates C++11/20 `constexpr`, compiles and runs on C++11 (GCC8) and also C++20, GCC10 and also contains the optional optimizations that I built this weekend

**Comment by johnmcfarlane** [comment]
I think I went and did the same thing: use naked `constexpr` for C++11-friendly usages and confined the `WIDE_INTEGER_CONSTEXPR` macro to functions where `constexpr` would not be allowed before C++20.

The macro is disabled for GCC-9 builds because that toolchain doesn't have a conforming standard library. Only Clang and GCC-10 have `WIDE_INTEGER_CONSTEXPR` set to `constexpr`.

Even after it passes CI, this change isn't ready to merge because it is based off of the #48 branch so that I can test both against one another. No hurry tho; still in the experimental phase I would say.

**Comment by ckormanyos** [comment]
Hi @johnmcfarlane it looks good to me.

I actually think its really neat to get a big integer at compile time.

So I manually integrated most of your changes to the [constexpr_11_and_20](https://github.com/ckormanyos/wide-integer/tree/constexpr_11_and_20).

This branch passed CI only _after_ I removed the `constexpr`-nes from Example5 `powm`, since some compilers reported that the depth of compile-time analysis had been exceeded in the Knuth long division routine.

**Comment by ckormanyos** [comment]
We are actually _almost_ ready for merge.

Your branch differs from my manual synchronization by 8 diffs in `uintwide_t`. Snips from my Araxis Merge show:

grafik

There are a few places where we have different spacing, you use the sequence `constexpr const` twice on PODs. Plus some discrepancies on these functions, where we have different `constexpr`opinions. You're probably correct on the unary operators, whereas I feel that the `double_width_type` cast operator must be C++20 `constexpr`.

grafik

**Comment by ckormanyos** [comment]
When we agree on these final changes, I feel like we are ready to merge the PR.

**Comment by ckormanyos** [comment]
Great work, John! You sure brought some new insight into this project that i did not previously have. Many thanks.

**Comment by ckormanyos** [comment]
Hi @johnmcfarlane could you please re-sync to #50 and comment on the remaining diffs? We should be very close to merging now.

**Comment by ckormanyos** [comment]
I also ran some tests on 8-bit and 32-bit embedded systems with compiler(s) going all the way back to 5.2. The work in #50, which is entirely based on this PR is good to go on preliminary embedded tests.

**Comment by johnmcfarlane** [comment]
> So I manually integrated most of your changes to the constexpr_11_and_20.

I did notice that you seem to be reapplying my changes in your own commits and then merging them into the main branch. I'm appreciative of the time and support you're providing and glad that the changes are being accepted. But this style of collaborating is unfamiliar to me and I wonder if I could recommend a more conventional approach.

Here's an ([example](https://githubflow.github.io/)) of a method of collaborating with which I'm a lot more familiar. I think it has a number of advantages:

* You can use GitHub's PR facilities to add review comments directly to the incoming changes. You can suggest changes there so it's clearer who is proposing/making the change and who is guiding with feedback.
* This in turn makes it less confusing when I pull latest _master_ and have to figure out why most of the changes in my branch have vanished. (I rely on the context of my branch history to remember what I'm doing, versus what's in the main branch.)
* Once the changes are merged, there's a clearer history of how they got there and who made them. That's useful for future developers (including me!) who need to understand how a change got in. I feel it also results in more accurate [attribution](https://github.com/ckormanyos/wide-integer/graphs/contributors).

Do you think this would be OK? I'm very familiar with this approach from work and home projects, including CNL, so let me know if you have any questions.

**Comment by ckormanyos** [comment]
>> So I manually integrated most of your changes to the constexpr_11_and_20.

> I did notice that you seem to be reapplying my changes in your own commits and then merging them into the main branch.

Yes. This was an interesting PR for me. Usually I work with a normal Git Flow. I found this to be a rather exceptional situation since there were something like 200 changes (with about 30 more coming from the embedded compilers).

I decided on purpose to examin each change line by line without the use of Git's merging.

Why? Because this thing amounted to a design change and honestly I needed to study the line by line changes.

When we get back to smaller line changes, I'll work the usual way. The manual merge of the CMake stuff was simply a mistake.

**Comment by ckormanyos** [comment]
This will all simmer down to normal very soon, John. Sorry about the unconventional manual merging. But it did really help me on this big scope of changes.

**Comment by ckormanyos** [comment]
Along those lines... @johnmcfarlane are you from your side now ready for the _normal_ Git merge?

If so, I'm good to go. I will have a little heap of secondary changes from the embedded compilers after than. Then we could wrap up this activity.

**Comment by ckormanyos** [comment]
I gotta admit, those embedded compilers GCC and clang from versions 5 through 10, 8 bit to 64 bit  really found some tricky stuff.

Took me 5 tries to get green on the embedded projects.

So give me a hollar when UR ready to merge this PR. Then I'll put the last embedded changes on top of that.

grafik

**Comment by johnmcfarlane** [comment]
There's not much left to merge now. Unless you think the last few changes are necessary, I'm happy to close the PR.

Regarding the errors in Example 5, this is a problem with performing computation at compile time. The compiler has no way of knowing whether a computation will complete and it's not allowed to stall indefinitely. So an arbitrary limit is placed on the number of steps it performs before giving up. Inevitably this number can be too small as I've found in CNL.

The solution is to increase the limit. Under Clang, the necessary option is: `-fconstexpr-steps=2000000`. Unfortunately, that's different to the equivalent GCC option so you cannot just pass it into both compilers.

Aside from passing separate flags to the build/configure commands there isn't a clean solution for this. You can put a kludge in the CMake scripts but I prefer to keep them compiler-agnostic where possible. One solution might involve a conditional Actions step a bit like [this](https://github.com/johnmcfarlane/cnl/blob/main/.github/workflows/test.yml#L176).

Would be interesting me proposing one of two things in order to increase the amount of constexpr-ness in those tests?

**Comment by ckormanyos** [comment]
> Unless you think the last few changes are necessary, I'm happy to close the PR

Merged, with many thanks @johnmcfarlane from my side.

CI is running and when it finishes, I will merge a few more changes of my own on top of this that were discovered with the embedded compiler(s).

> Would be interesting me proposing one of two things in order to increase the amount of constexpr-ness in those tests?

Yes. But I am also extremely happy with the state of `constexpr`-ness. Do you know that I just cut a constant valued big integer on code for an embedded ARM Cortex-M0 constroller (in an unpublished project) using `arm-none-eabi` GCC 10? It is great!

**Comment by ckormanyos** [comment]
After that, the questions of signed-ness and possibly migrating to an org, we will handle.

**Pull request merged**
